apiVersion: v1
kind: ServiceAccount
metadata:
 name: cluster-admin-sa
 namespace: security-webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: security-webapp
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""